/**
 * @file Database Schema Definition for Ghar-Bhandaa.
 * @description Defines the SQLite schema using Drizzle ORM for Cloudflare D1.
 *
 * The schema comprises two primary categories:
 * 1. Better Auth Tables: Core authentication tables (`user`, `session`, `account`, `verification`).
 * 2. Multi-Tenant Domain Tables: Property rental domain tables (`landlords`, `properties`, `rooms`,
 *    `tenants`, `leases`, `invoices`, `invoiceLineItems`, `payments`, `notificationsLog`).
 *
 * Key Architectural Invariants:
 * - Integer Paisa Arithmetic: All monetary fields (`rentAmount`, `depositAmount`, `amount`) are stored
 *   as integer paisa (1 NPR = 100 Paisa). Floating point currency math in DB is prohibited.
 * - Multi-Tenant Isolation: Every tenant, property, room, lease, invoice, and payment is partitioned by `landlordId`.
 * - Append-Only Payment Ledger: Payments are recorded as immutable event rows.
 * - Deterministic Invoice Status: Invoices derive state from confirmed payment aggregates and due dates.
 */

import {
  sqliteTable,
  text,
  integer,
  uniqueIndex,
  index,
} from 'drizzle-orm/sqlite-core'

// ============================================================================
// Better Auth Tables
// ============================================================================

/**
 * Better Auth User Table.
 * Represents registered users across the application.
 *
 * @remarks
 * In Ghar-Bhandaa, each authenticated landlord user corresponds 1:1 with an entry
 * in the domain `landlords` table via matching `id`.
 */
export const user = sqliteTable('user', {
  /** Primary identifier (UUID string generated by Better Auth) */
  id: text('id').primaryKey(),
  /** Full name of the user */
  name: text('name').notNull(),
  /** Unique email address */
  email: text('email').notNull().unique(),
  /** Boolean flag indicating whether email has been verified */
  emailVerified: integer('email_verified', { mode: 'boolean' }).notNull(),
  /** Optional profile image URL */
  image: text('image'),
  /** Creation timestamp */
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
  /** Last update timestamp */
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
})

/**
 * Better Auth Session Table.
 * Stores active session tokens for user authentication.
 */
export const session = sqliteTable('session', {
  /** Primary identifier of the session */
  id: text('id').primaryKey(),
  /** Expiration timestamp for the session */
  expiresAt: integer('expires_at', { mode: 'timestamp' }).notNull(),
  /** Unique secret session token */
  token: text('token').notNull().unique(),
  /** Creation timestamp */
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
  /** Last update timestamp */
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
  /** Client IP address associated with the session */
  ipAddress: text('ip_address'),
  /** Client User-Agent string */
  userAgent: text('user_agent'),
  /** Foreign key reference to the `user` table (cascades on delete) */
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
})

/**
 * Better Auth Account Table.
 * Stores credentials, OAuth accounts, and linked provider authentications.
 */
export const account = sqliteTable('account', {
  /** Primary identifier of the linked account */
  id: text('id').primaryKey(),
  /** Account ID from the authentication provider */
  accountId: text('account_id').notNull(),
  /** Provider identifier (e.g. 'credential', 'google') */
  providerId: text('provider_id').notNull(),
  /** Foreign key reference to the `user` table (cascades on delete) */
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  /** OAuth access token */
  accessToken: text('access_token'),
  /** OAuth refresh token */
  refreshToken: text('refresh_token'),
  /** OAuth ID token */
  idToken: text('id_token'),
  /** Expiration timestamp for access token */
  accessTokenExpiresAt: integer('access_token_expires_at', {
    mode: 'timestamp',
  }),
  /** Expiration timestamp for refresh token */
  refreshTokenExpiresAt: integer('refresh_token_expires_at', {
    mode: 'timestamp',
  }),
  /** Granted OAuth scopes */
  scope: text('scope'),
  /** Hashed password for email/password provider */
  password: text('password'),
  /** Creation timestamp */
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
  /** Last update timestamp */
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
})

/**
 * Better Auth Verification Table.
 * Stores temporary verification tokens for email verification and password resets.
 */
export const verification = sqliteTable('verification', {
  /** Primary identifier of the verification record */
  id: text('id').primaryKey(),
  /** Identifier being verified (e.g., email address) */
  identifier: text('identifier').notNull(),
  /** Verification token value */
  value: text('value').notNull(),
  /** Expiration timestamp of the token */
  expiresAt: integer('expires_at', { mode: 'timestamp' }).notNull(),
  /** Creation timestamp */
  createdAt: integer('created_at', { mode: 'timestamp' }),
  /** Last update timestamp */
  updatedAt: integer('updated_at', { mode: 'timestamp' }),
})

// ============================================================================
// Multi-Tenant Property Rental Domain Tables
// ============================================================================

/**
 * Landlords Domain Table.
 * Stores landlord profile information and serves as the tenancy root for multi-tenant isolation.
 *
 * @remarks
 * The `id` primary key maps 1:1 to Better Auth's `user.id`.
 */
export const landlords = sqliteTable('landlords', {
  /** Primary identifier (maps directly to `user.id`) */
  id: text('id').primaryKey(),
  /** Unique email address of the landlord */
  email: text('email').notNull().unique(),
  /** Landlord full name */
  name: text('name').notNull(),
  /** Contact phone number */
  phone: text('phone'),
  /** Creation timestamp (ISO-8601 string) */
  createdAt: text('created_at').notNull(),
})

/**
 * Properties Table.
 * Represents physical buildings, houses, or compounds managed by a landlord.
 */
export const properties = sqliteTable(
  'properties',
  {
    /** Primary UUID identifier */
    id: text('id').primaryKey(),
    /** Tenancy foreign key reference to `landlords.id` */
    landlordId: text('landlord_id')
      .notNull()
      .references(() => landlords.id),
    /** Display name of the property (e.g. 'Kathmandu Villa', 'Patan Heights') */
    name: text('name').notNull(),
    /** Full physical street address */
    address: text('address').notNull(),
    /** Creation timestamp (ISO-8601 string) */
    createdAt: text('created_at').notNull(),
  },
  (table) => [index('properties_landlord_idx').on(table.landlordId)],
)

/**
 * Rooms Table.
 * Represents individual rentable units, rooms, or flats within a property.
 */
export const rooms = sqliteTable(
  'rooms',
  {
    /** Primary UUID identifier */
    id: text('id').primaryKey(),
    /** Tenancy foreign key reference to `landlords.id` */
    landlordId: text('landlord_id')
      .notNull()
      .references(() => landlords.id),
    /** Foreign key reference to parent `properties.id` */
    propertyId: text('property_id')
      .notNull()
      .references(() => properties.id),
    /** Room number or name (e.g. 'Room 101', 'Flat 2B') */
    name: text('name').notNull(),
    /** Floor level description (e.g. '1st Floor', 'Ground Floor') */
    floor: text('floor'),
    /** Additional description or notes about the room */
    description: text('description'),
    /** Active status flag indicating availability or readiness */
    isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
    /** Creation timestamp (ISO-8601 string) */
    createdAt: text('created_at').notNull(),
  },
  (table) => [
    index('rooms_landlord_idx').on(table.landlordId),
    index('rooms_property_idx').on(table.propertyId),
    index('rooms_landlord_property_idx').on(table.landlordId, table.propertyId),
  ],
)

/**
 * Tenants Table.
 * Directory of tenants registered under a landlord.
 *
 * @remarks
 * Contains a composite unique index on `(landlordId, email)` allowing distinct landlords
 * to independently register the same tenant email address without collision.
 */
export const tenants = sqliteTable(
  'tenants',
  {
    /** Primary UUID identifier */
    id: text('id').primaryKey(),
    /** Tenancy foreign key reference to `landlords.id` */
    landlordId: text('landlord_id')
      .notNull()
      .references(() => landlords.id),
    /** Full name of the tenant */
    name: text('name').notNull(),
    /** Tenant email address */
    email: text('email').notNull(),
    /** Tenant contact phone number */
    phone: text('phone'),
    /** Internal notes regarding the tenant */
    notes: text('notes'),
    /** Creation timestamp (ISO-8601 string) */
    createdAt: text('created_at').notNull(),
  },
  (table) => [
    index('tenants_landlord_idx').on(table.landlordId),
    uniqueIndex('tenants_landlord_email_idx').on(table.landlordId, table.email),
  ],
)

/**
 * Leases Table.
 * Represents a rental agreement between a tenant and a room under a landlord.
 *
 * @remarks
 * - Monetary amounts (`rentAmount`, `depositAmount`) are stored in integer paisa (1 NPR = 100 Paisa).
 * - `billingDay` is constrained between 1 and 28 to ensure validity across all calendar months including February.
 */
export const leases = sqliteTable(
  'leases',
  {
    /** Primary UUID identifier */
    id: text('id').primaryKey(),
    /** Tenancy foreign key reference to `landlords.id` */
    landlordId: text('landlord_id')
      .notNull()
      .references(() => landlords.id),
    /** Foreign key reference to `rooms.id` */
    roomId: text('room_id')
      .notNull()
      .references(() => rooms.id),
    /** Foreign key reference to `tenants.id` */
    tenantId: text('tenant_id')
      .notNull()
      .references(() => tenants.id),
    /** Recurring rent amount stored in integer paisa (1 NPR = 100 Paisa) */
    rentAmount: integer('rent_amount').notNull(),
    /** Security deposit amount stored in integer paisa */
    depositAmount: integer('deposit_amount').notNull(),
    /** Day of the month (1-28) when recurring monthly invoices are billed */
    billingDay: integer('billing_day').notNull(),
    /** Lease start date formatted as YYYY-MM-DD */
    startDate: text('start_date').notNull(),
    /** Optional lease termination date formatted as YYYY-MM-DD */
    endDate: text('end_date'),
    /** Lifecycle status of the lease: 'active' | 'ended' */
    status: text('status').notNull().default('active'),
    /** Creation timestamp (ISO-8601 string) */
    createdAt: text('created_at').notNull(),
  },
  (table) => [
    index('leases_landlord_idx').on(table.landlordId),
    index('leases_room_idx').on(table.roomId),
    index('leases_tenant_idx').on(table.tenantId),
  ],
)

/**
 * Invoices Table.
 * Monthly billing statements issued for active leases.
 *
 * @remarks
 * - Enforces idempotency via unique index on `(leaseId, period)` (e.g. only one invoice per lease per `YYYY-MM`).
 * - `amount` is stored in integer paisa representing the denormalized total of line items.
 * - `status` is derived deterministically: 'unpaid' | 'partial' | 'paid' | 'overdue'.
 */
export const invoices = sqliteTable(
  'invoices',
  {
    /** Primary UUID identifier */
    id: text('id').primaryKey(),
    /** Tenancy foreign key reference to `landlords.id` */
    landlordId: text('landlord_id')
      .notNull()
      .references(() => landlords.id),
    /** Foreign key reference to `leases.id` */
    leaseId: text('lease_id')
      .notNull()
      .references(() => leases.id),
    /** Foreign key reference to `tenants.id` */
    tenantId: text('tenant_id')
      .notNull()
      .references(() => tenants.id),
    /** Billing period represented as YYYY-MM (e.g. '2026-08') */
    period: text('period').notNull(),
    /** Denormalized total invoice amount stored in integer paisa */
    amount: integer('amount').notNull(),
    /** Payment due date formatted as YYYY-MM-DD in Asia/Kathmandu timezone */
    dueDate: text('due_date').notNull(),
    /** Derived invoice status: 'unpaid' | 'partial' | 'paid' | 'overdue' */
    status: text('status').notNull().default('unpaid'),
    /** Creation timestamp (ISO-8601 string) */
    createdAt: text('created_at').notNull(),
    /** Last updated timestamp (ISO-8601 string) */
    updatedAt: text('updated_at').notNull(),
  },
  (table) => [
    index('invoices_landlord_idx').on(table.landlordId),
    index('invoices_tenant_idx').on(table.tenantId),
    index('invoices_lease_idx').on(table.leaseId),
    uniqueIndex('invoices_lease_period_idx').on(table.leaseId, table.period),
  ],
)

/**
 * Invoice Line Items Table.
 * Itemized breakdown of charges contributing to an invoice.
 */
export const invoiceLineItems = sqliteTable(
  'invoice_line_items',
  {
    /** Primary UUID identifier */
    id: text('id').primaryKey(),
    /** Foreign key reference to parent `invoices.id` (cascades on delete) */
    invoiceId: text('invoice_id')
      .notNull()
      .references(() => invoices.id, { onDelete: 'cascade' }),
    /** Line item description (e.g., 'Monthly Room Rent', 'Electricity Charge (15 units)') */
    description: text('description').notNull(),
    /** Line item amount in integer paisa */
    amount: integer('amount').notNull(),
    /** Category of charge: 'rent' | 'utility' | 'adjustment' */
    kind: text('kind').notNull(),
  },
  (table) => [index('invoice_line_items_invoice_idx').on(table.invoiceId)],
)

/**
 * Payments Table.
 * Append-only financial ledger of payments made towards invoices.
 *
 * @remarks
 * - Stored in integer paisa.
 * - Supports payment methods: 'khalti' | 'esewa' | 'bank_transfer' | 'cash'.
 * - Cash payments are confirmed immediately upon recording; bank transfers require landlord proof verification.
 */
export const payments = sqliteTable(
  'payments',
  {
    /** Primary UUID identifier */
    id: text('id').primaryKey(),
    /** Tenancy foreign key reference to `landlords.id` */
    landlordId: text('landlord_id')
      .notNull()
      .references(() => landlords.id),
    /** Foreign key reference to associated `invoices.id` */
    invoiceId: text('invoice_id')
      .notNull()
      .references(() => invoices.id),
    /** Foreign key reference to `tenants.id` */
    tenantId: text('tenant_id')
      .notNull()
      .references(() => tenants.id),
    /** Payment amount stored in integer paisa */
    amount: integer('amount').notNull(),
    /** Payment method: 'khalti' | 'esewa' | 'bank_transfer' | 'cash' */
    method: text('method').notNull(),
    /** Ledger payment status: 'initiated' | 'pending_verification' | 'confirmed' | 'rejected' | 'failed' */
    status: text('status').notNull().default('initiated'),
    /** Unique gateway transaction reference ID (Khalti/eSewa) */
    gatewayRef: text('gateway_ref'),
    /** Reference number / remark typed by tenant for manual bank transfers */
    bankRef: text('bank_ref'),
    /** Cloudflare R2 object key pointing to uploaded payment screenshot / voucher */
    proofObjectKey: text('proof_object_key'),
    /** Creation timestamp (ISO-8601 string) */
    createdAt: text('created_at').notNull(),
    /** Confirmation timestamp (ISO-8601 string) when funds were verified */
    confirmedAt: text('confirmed_at'),
  },
  (table) => [
    index('payments_landlord_idx').on(table.landlordId),
    index('payments_invoice_idx').on(table.invoiceId),
    index('payments_tenant_idx').on(table.tenantId),
    uniqueIndex('payments_gateway_ref_idx').on(table.gatewayRef),
  ],
)

/**
 * Notifications Log Table.
 * Audit trail of automated and manual outbound tenant notifications (email/SMS).
 */
export const notificationsLog = sqliteTable(
  'notifications_log',
  {
    /** Primary UUID identifier */
    id: text('id').primaryKey(),
    /** Tenancy foreign key reference to `landlords.id` */
    landlordId: text('landlord_id')
      .notNull()
      .references(() => landlords.id),
    /** Optional foreign key reference to relevant `invoices.id` */
    invoiceId: text('invoice_id').references(() => invoices.id),
    /** Foreign key reference to recipient `tenants.id` */
    tenantId: text('tenant_id')
      .notNull()
      .references(() => tenants.id),
    /** Notification delivery channel: 'email' | 'sms' */
    channel: text('channel').notNull(),
    /** Notification trigger kind: 'reminder_before' | 'reminder_due' | 'reminder_overdue' | 'receipt' */
    kind: text('kind').notNull(),
    /** Timestamp when notification was dispatched */
    sentAt: text('sent_at').notNull(),
    /** Delivery outcome: 'sent' | 'failed' */
    status: text('status').notNull(),
  },
  (table) => [
    index('notifications_log_landlord_idx').on(table.landlordId),
    index('notifications_log_invoice_idx').on(table.invoiceId),
    index('notifications_log_tenant_idx').on(table.tenantId),
    index('notifications_log_invoice_kind_idx').on(table.invoiceId, table.kind),
  ],
)
