/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedTenantsRouteImport } from './routes/_authed/tenants'
import { Route as AuthedRoomsRouteImport } from './routes/_authed/rooms'
import { Route as AuthedPropertiesRouteImport } from './routes/_authed/properties'
import { Route as AuthedLeasesRouteImport } from './routes/_authed/leases'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedInvoicesInvoiceIdRouteImport } from './routes/_authed/invoices.$invoiceId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTenantsRoute = AuthedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRoomsRoute = AuthedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPropertiesRoute = AuthedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLeasesRoute = AuthedLeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedInvoicesInvoiceIdRoute = AuthedInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/leases': typeof AuthedLeasesRoute
  '/properties': typeof AuthedPropertiesRoute
  '/rooms': typeof AuthedRoomsRoute
  '/tenants': typeof AuthedTenantsRoute
  '/invoices/$invoiceId': typeof AuthedInvoicesInvoiceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/leases': typeof AuthedLeasesRoute
  '/properties': typeof AuthedPropertiesRoute
  '/rooms': typeof AuthedRoomsRoute
  '/tenants': typeof AuthedTenantsRoute
  '/invoices/$invoiceId': typeof AuthedInvoicesInvoiceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/leases': typeof AuthedLeasesRoute
  '/_authed/properties': typeof AuthedPropertiesRoute
  '/_authed/rooms': typeof AuthedRoomsRoute
  '/_authed/tenants': typeof AuthedTenantsRoute
  '/_authed/invoices/$invoiceId': typeof AuthedInvoicesInvoiceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/leases'
    | '/properties'
    | '/rooms'
    | '/tenants'
    | '/invoices/$invoiceId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/leases'
    | '/properties'
    | '/rooms'
    | '/tenants'
    | '/invoices/$invoiceId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/login'
    | '/signup'
    | '/_authed/dashboard'
    | '/_authed/leases'
    | '/_authed/properties'
    | '/_authed/rooms'
    | '/_authed/tenants'
    | '/_authed/invoices/$invoiceId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/tenants': {
      id: '/_authed/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthedTenantsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/rooms': {
      id: '/_authed/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthedRoomsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/properties': {
      id: '/_authed/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthedPropertiesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/leases': {
      id: '/_authed/leases'
      path: '/leases'
      fullPath: '/leases'
      preLoaderRoute: typeof AuthedLeasesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/invoices/$invoiceId': {
      id: '/_authed/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthedInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedLeasesRoute: typeof AuthedLeasesRoute
  AuthedPropertiesRoute: typeof AuthedPropertiesRoute
  AuthedRoomsRoute: typeof AuthedRoomsRoute
  AuthedTenantsRoute: typeof AuthedTenantsRoute
  AuthedInvoicesInvoiceIdRoute: typeof AuthedInvoicesInvoiceIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedLeasesRoute: AuthedLeasesRoute,
  AuthedPropertiesRoute: AuthedPropertiesRoute,
  AuthedRoomsRoute: AuthedRoomsRoute,
  AuthedTenantsRoute: AuthedTenantsRoute,
  AuthedInvoicesInvoiceIdRoute: AuthedInvoicesInvoiceIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
